In [2]:
import numpy as np #import library first


In [2]:
a=np.array([1,2,2,3,2,6])  # create a array 
a

array([1, 2, 2, 3, 2, 6])

In [5]:
b=np.array([[2,34,2,4,56,2],[2,3,4,5,2,5]]) # create number of dimension in array.
b

array([[ 2, 34,  2,  4, 56,  2],
       [ 2,  3,  4,  5,  2,  5]])

In [6]:
type(b)  # check the array type

numpy.ndarray

In [7]:
b.ndim  # check the number of dimension

2

In [11]:
d=np.array([2,34,2,4,56] , ndmin=5)  # ndmin means declare the number of dimension
d

array([[[[[ 2, 34,  2,  4, 56]]]]])

In [12]:
d.ndim

5

In [13]:
print(d.shape)  #check the shape of array which is stored in the dimension

(1, 1, 1, 1, 5)


In [18]:
print(d.reshape(1,5))  # convert row and columns in different way.

[[[ 2 34  2  4 56]]]


In [4]:
h = np.array([[[3,5,7]],[[7,8,8]]])
print(h)
print("shape:" , h.shape)
print("reshape: ", h.reshape(1,3,2))

[[[3 5 7]]

 [[7 8 8]]]
shape: (2, 1, 3)
reshape:  [[[3 5]
  [7 7]
  [8 8]]]


In [5]:
print(h[0,0,1] + h[0,0,1] + h[0,0,1]) #Add the value using indexing store in the array

15


In [34]:
v=np.array([1,3,4,2,6])
print("v =",v)
n=v.copy() #Copy method is used for create a copy of the array.
print("n = ",n)

v = [1 3 4 2 6]
n =  [1 3 4 2 6]


In [35]:
n[2]=5
print(n)

[1 3 5 2 6]


In [38]:
print("v=",v) # copy method doesnot change the original data.
print("n=",n)

v= [1 3 4 2 6]
n= [1 3 5 2 6]


In [42]:
j=np.array([1,2,3,2])
print("j=",j)
p=j.view()  # using view method do changes in original data...
print("p=",p)

j= [1 2 3 2]
p= [1 2 3 2]


In [44]:
p[1]=10
print(p)

[ 1 10  3  2]


In [45]:
print("j=",j)    # changes make in original data.
print("p=",p)

j= [ 1 10  3  2]
p= [ 1 10  3  2]


In [48]:
np.ones((5))    # ones function is used for creating the array using one.

array([1., 1., 1., 1., 1.])

In [49]:
np.ones((5,2))  #also give the shape of the array..

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [54]:
np.ones((5,2),dtype =np.int64) #Also change the datatypes of the array

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int64)

In [51]:
np.zeros((6))  # zeros means creating array using zero.

array([0., 0., 0., 0., 0., 0.])

In [53]:
np.zeros((6,3))  # Also give the shape of the array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])